name = "All the Mods 10"
author = "ATMTeam"
version = "6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39086f2a131f46549c9a164e4215fd053d7e4e14bb3c59973703958fb0caddcc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
