name = "All the Mods 10"
author = "ATMTeam"
version = "6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ec0e9fa0e2eb5b16874d362b4868f139686f12d5d807fc6a3cb8af73290d8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
