name = "All the Mods 10"
author = "ATMTeam"
version = "6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f71e940d3968a265fe67db80ed2d63d60df13f1ad8e17c00d75055dce8db4b20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
